import { ReactNode } from 'react';
import type { Database } from '../lib/database.types';

type RanchSettings = Database['public']['Tables']['ranch_settings']['Row'];

interface PrintableReportProps {
  title: string;
  settings: RanchSettings | null;
  children: ReactNode;
}

export function PrintableReport({ title, settings, children }: PrintableReportProps) {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="print:p-8">
      <div className="mb-8 text-center border-b-2 border-gray-800 pb-4">
        {settings?.report_line1 && (
          <h1 className="text-2xl font-bold text-gray-900 mb-1">{settings.report_line1}</h1>
        )}
        {settings?.report_line2 && (
          <p className="text-lg text-gray-700 mb-2">{settings.report_line2}</p>
        )}
        <h2 className="text-xl font-semibold text-gray-900 mt-3">{title}</h2>
        <p className="text-sm text-gray-600 mt-1">{currentDate}</p>
      </div>

      <div className="space-y-6">
        {children}
      </div>

      <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500 print:block hidden">
        <p>Generated by AmadorHerdInfo - Amador Software</p>
      </div>
    </div>
  );
}

export function ReportSection({ title, children }: { title?: string; children: ReactNode }) {
  return (
    <div className="mb-6">
      {title && <h3 className="text-lg font-semibold text-gray-900 mb-3">{title}</h3>}
      {children}
    </div>
  );
}

export function ReportTable({
  headers,
  rows
}: {
  headers: string[];
  rows: (string | number)[][];
}) {
  return (
    <table className="min-w-full border border-gray-300">
      <thead className="bg-gray-100">
        <tr>
          {headers.map((header, i) => (
            <th
              key={i}
              className="px-4 py-2 text-left text-sm font-semibold text-gray-900 border-b border-gray-300"
            >
              {header}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, i) => (
          <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
            {row.map((cell, j) => (
              <td
                key={j}
                className="px-4 py-2 text-sm text-gray-900 border-b border-gray-200"
              >
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export function ReportGrid({
  items
}: {
  items: { label: string; value: string | number }[];
}) {
  return (
    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
      {items.map((item, i) => (
        <div key={i} className="border border-gray-300 rounded-lg p-4 bg-white">
          <div className="text-sm font-medium text-gray-600 mb-1">{item.label}</div>
          <div className="text-2xl font-bold text-gray-900">{item.value}</div>
        </div>
      ))}
    </div>
  );
}
